#pragma config(Sensor, S1,     frontSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     floorColor,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     wallSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Flags
bool FRONTFLAG;
bool WALLFLAG;
bool COLORFLAG;

//Actions
int FRONTCMD;
int WALLCMD;
int COLORCMD;


//Motor Tasks------------------------------------------------------------------------

//turn 90 degrees left
void turnLeft90()
{
	setMotorSyncTime(leftMotor, rightMotor, -100, 300, 50);
	sleep(500);
}

//turn 90 degrees right
void turnRight90()
{
	setMotorSyncTime(leftMotor, rightMotor, 100, 300, 48);
	sleep(500);
}

//Sensor Tasks-------------------------------------------------------------------------
task frontSonarTask()
{
	while(true)
	{
		hogCPU();
		if(sensorValue(frontSonar) < 10)
		{
			FRONTFLAG = true; //something is blocking BW.
		}

		else
		{
			FRONTFLAG = false;
		}

		releaseCPU();
	}
}

task wallSonarTask()
{
	while(true)
	{
		if(sensorValue(wallSonar) > 30)
		{
			WALLFLAG = true;
		}
		else
		{
			WALLFLAG = false;
		}
	}
}

void justDoIt(int command)
{
	switch(command)
	{
		case 0:
		//do nothing
		break;

		case 1:
		//Wall flag
		break;

		case 2:
			turnLeft90();
		break;

		default:
		break;
	}
}

task main()
{
	startTask(frontSonarTask);
	startTask(wallSonarTask);
	int command;
	while(true)
	{
		hogcpu();
		command = 0;

		if(WALLFLAG)
		{
			command = 1;
		}

		if(FRONTFLAG)
		{
			command = 2;
		}

		justDoIt(command);
		releasecpu();
	}




}
